# .travis.yml
language: go

# calls goreleaser
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | GO111MODULE=on bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
